### ISSUE TITLE
Unable to resolve path to module 'react-day-picker/dist/style.css'

### ISSUE THREAD

**Issue by shareef-dweikat** [gpbl/react-day-picker#2516]
Hi,

```tsx
import {
  DayPicker,
  DateRange,
  ClassNames,
  DayPickerRangeProps,
  DayPickerSingleProps,
} from 'react-day-picker';
import 'react-day-picker/dist/style.css';
```

## Actual Behavior
The build fails due to "Unable to resolve path to module 'react-day-picker/dist/style.css'" error

**Comment by karlshea** [comment]
I had similar issues importing into a Sass stylesheet, there are multiple style exports in the package.json and they're not resolving. When I finally did get one to resolve there was an additional error because the "default" key isn't last ("types" is getting added after it).

I finally got it to work by using `@use` instead of `@import` and using a relative path to the source in node_modules.

**Comment by shareef-dweikat** [comment]
@karlshea Thanks
My case might be a little different. I am trying to import it into tsx file, not a Sass. 
Your solution wont work for me.

**Comment by gpbl** [comment]
👋 The correct path for the style is either `react-day-picker/style.css` or `react-day-picker/style.module.css`.

If you're _really_ having issues importing these, the source file is located at `react-day-picker/src/style.css` (in the `/src` directory).

PS. In v9.1.4, we addressed some compatibility issues with older build systems—could you please give it a test? Thanks!

**Comment by shareef-dweikat** [comment]
@gpbl Thanks

Importing from the source directly is not working (Unable to resolve path to module 'react-day-picker/src/style.css')
I have upgraded to v9.1.4, i get same errors.

I am using create-react-app

**Comment by gpbl** [comment]
@shareef-dweikat The import path is `react-day-picker/style.css`. 

I don’t have any issues importing it using create-react-app. If you believe this is a bug in DayPicker, please reproduce the bug on stackblitz.com or codesandbox.io and open a [support discussion](https://github.com/gpbl/react-day-picker/discussions). Thanks!

**Comment by karlshea** [comment]
It's still not working using sass-loader and webpack, follow up here: https://github.com/gpbl/react-day-picker/discussions/2546
